/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userInterface.corporateRole;

import business.EcoSystem;
import business.enterprise.Enterprise;
import business.enterprise.FundEnterprise;
import business.network.Network;
import business.organization.FundraiserOrganization;
import business.userAccount.UserAccount;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author dhairyasheel
 */
public class CorporateFundRaiserJPanel extends javax.swing.JPanel {

    /**
     * Creates new form CorporateFundRaiserJPanel
     */
    JPanel userProcessContainer;
    FundEnterprise enterprise;
    UserAccount userAccount;
    Network network;
    EcoSystem system;
    FundraiserOrganization organization;
    public CorporateFundRaiserJPanel(JPanel userProcessContainer, UserAccount account, FundraiserOrganization organization, FundEnterprise enterprise, Network network, EcoSystem business) {
        this.userProcessContainer = userProcessContainer;
        this.enterprise = enterprise;
        this.userAccount = account;
        this.network = network;
        this.system = business;
        this.organization = organization;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btnRaiseFund = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        txtmoney = new javax.swing.JTextField();

        jLabel1.setText("Corporate Donate Funds");

        btnRaiseFund.setText("Raise fund");
        btnRaiseFund.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRaiseFundActionPerformed(evt);
            }
        });

        jLabel2.setText("Enter Amount to Donate");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(179, 179, 179)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(85, 85, 85)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(138, 138, 138)
                                .addComponent(btnRaiseFund))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtmoney, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(177, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(108, 108, 108)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtmoney, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addComponent(btnRaiseFund)
                .addContainerGap(163, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnRaiseFundActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRaiseFundActionPerformed
        // TODO add your handling code here:
        try{
                    enterprise.setFundsCollected(Integer.parseInt(txtmoney.getText()));
                    System.out.println(enterprise.getFundsCollected());
                    JOptionPane.showMessageDialog(null, "You have donated " +txtmoney.getText()+ "$. Thank you for your valuable contribution! " +"\n"+" Funds Sent to System Admin for Assigning Hospital!");
                }catch(NumberFormatException ex){
                  //   System.out.println(e.getFundsCollected());
                     JOptionPane.showMessageDialog(null, "Please Enter The Amount you want to donate in digits");
                }
    }//GEN-LAST:event_btnRaiseFundActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnRaiseFund;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTextField txtmoney;
    // End of variables declaration//GEN-END:variables
}
