/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userInterface.registration;

import business.EcoSystem;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import userInterface.AdminFundRole.GeneralRegisterJPanel;

/**
 *
 * @author dhairyasheel
 */
public class RegistrationForms extends javax.swing.JPanel {

    /**
     * Creates new form RegistrationForms
     */
   private JPanel userProcessContainer;
    private EcoSystem system;
    public RegistrationForms(JPanel userProcessContainerÏ, EcoSystem system) {
        initComponents();
        this.system = system;
        this.userProcessContainer = userProcessContainerÏ;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDesktopPane1 = new javax.swing.JDesktopPane();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        registerCombo = new javax.swing.JComboBox<>();
        registrationMain = new javax.swing.JPanel();

        setBackground(new java.awt.Color(254, 254, 254));

        jLabel1.setBackground(new java.awt.Color(254, 254, 254));
        jLabel1.setFont(new java.awt.Font("Serif", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(96, 109, 146));
        jLabel1.setText("Registration Form");

        jLabel2.setFont(new java.awt.Font("Serif", 1, 14)); // NOI18N
        jLabel2.setText("Registration for:");

        registerCombo.setBackground(new java.awt.Color(254, 254, 254));
        registerCombo.setFont(new java.awt.Font("Serif", 1, 14)); // NOI18N
        registerCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select", "Shelter/Health for Self", "Shelter/Health for Needy", "Fund Donation" }));
        registerCombo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                registerComboMouseClicked(evt);
            }
        });
        registerCombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registerComboActionPerformed(evt);
            }
        });

        registrationMain.setBackground(new java.awt.Color(254, 254, 254));
        registrationMain.setLayout(new java.awt.CardLayout());

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(281, 281, 281)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(registrationMain, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(registerCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 282, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 336, Short.MAX_VALUE)))))
                .addGap(42, 42, 42))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(registerCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(registrationMain, javax.swing.GroupLayout.DEFAULT_SIZE, 408, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void registerComboMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_registerComboMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_registerComboMouseClicked

    private void registerComboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registerComboActionPerformed
        // TODO add your handling code here:
        String selectedString = (String) registerCombo.getSelectedItem();
        if(selectedString.equalsIgnoreCase("Shelter/Health for Self")){
            SelfRegistrationJPanel fundPanel = new SelfRegistrationJPanel(userProcessContainer,system);
            registrationMain.add("GeneralRegistrationJPanel", fundPanel);
            CardLayout layout = (CardLayout) registrationMain.getLayout();
            layout.next(registrationMain);
        } else if(selectedString.equalsIgnoreCase("Shelter/Health for Needy")){
            RegistrationNeedyJPanel fundPanel = new RegistrationNeedyJPanel(userProcessContainer,system);
            registrationMain.add("RegistrationNeedyJPanel", fundPanel);
            CardLayout layout = (CardLayout) registrationMain.getLayout();
            layout.next(registrationMain);
        } else if(selectedString.equalsIgnoreCase("Fund Donation")){
            FundRegistrationJPanel fundPanel = new FundRegistrationJPanel(userProcessContainer,system);
            registrationMain.add("FundRegistrationJPanel", fundPanel);
            CardLayout layout = (CardLayout) registrationMain.getLayout();
            layout.next(registrationMain);
        } else{
            JOptionPane.showMessageDialog(this, "Select form the options provided");
        }
    }//GEN-LAST:event_registerComboActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JComboBox<String> registerCombo;
    private javax.swing.JPanel registrationMain;
    // End of variables declaration//GEN-END:variables
}
