/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userInterface.registration;

import business.EcoSystem;
import business.enterprise.Enterprise;
import business.network.Network;
import business.roles.AdminRole;
import business.userAccount.UserAccount;
import business.workQueue.PatientTestRequest;
import business.workQueue.ShelterRequest;
import java.awt.Graphics2D;
import java.awt.Image;
import java.awt.image.BufferedImage;
import static java.awt.image.ImageObserver.PROPERTIES;
import java.awt.image.RenderedImage;
import java.util.Optional;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import java.io.File;
import java.io.IOException;
import java.lang.System.Logger;
import java.lang.System.Logger.Level;
import java.net.MalformedURLException;
import java.net.URL;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import javax.imageio.ImageIO;
import javax.swing.filechooser.FileNameExtensionFilter;
import userInterface.PersonalDetailsJPanel;
/**
 *
 * @author dhairyasheel
 */
public class RegistrationNeedyJPanel extends javax.swing.JPanel {

    /**
     * Creates new form RegistrationJPanel
     */
    private JPanel userProcessContainer;
    private EcoSystem system;
    private final JFileChooser fileChooser = new JFileChooser();
//    ImageIcon logoImage;
    RenderedImage needyPicture;
    
    public RegistrationNeedyJPanel(JPanel userProcessContainer, EcoSystem system) {
        initComponents();
        this.system = system;
        this.userProcessContainer = userProcessContainer;
        populateComboBox(); 
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        addjPanel4 = new javax.swing.JPanel();
        lblCourseCode1 = new javax.swing.JLabel();
        txtEmail = new javax.swing.JTextField();
        lblCourseName1 = new javax.swing.JLabel();
        cPhone = new javax.swing.JTextField();
        lblCredits2 = new javax.swing.JLabel();
        cPerson = new javax.swing.JTextField();
        lblCredits4 = new javax.swing.JLabel();
        cmbRequestType = new javax.swing.JComboBox<>();
        lblCredits3 = new javax.swing.JLabel();
        networkJComboBox = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        addjPanel3 = new javax.swing.JPanel();
        lblCourseCode = new javax.swing.JLabel();
        fName = new javax.swing.JTextField();
        lblCourseName = new javax.swing.JLabel();
        lName = new javax.swing.JTextField();
        lblkeywords = new javax.swing.JLabel();
        lblCredits = new javax.swing.JLabel();
        age = new javax.swing.JTextField();
        jdcDOB = new com.toedter.calendar.JDateChooser();
        lblCredits1 = new javax.swing.JLabel();
        genderCombo = new javax.swing.JComboBox<>();
        lblCourseCode2 = new javax.swing.JLabel();
        height = new javax.swing.JTextField();
        lblCourseCode5 = new javax.swing.JLabel();
        lblCourseCode3 = new javax.swing.JLabel();
        weight = new javax.swing.JTextField();
        lblCourseCode4 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        imgLogo = new javax.swing.JLabel();
        btnAttach = new javax.swing.JButton();

        setBackground(new java.awt.Color(251, 251, 251));

        addjPanel4.setBackground(new java.awt.Color(254, 254, 254));
        addjPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createTitledBorder(""), "Details of Person Helping", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Ubuntu", 1, 15), new java.awt.Color(95, 139, 162))); // NOI18N

        lblCourseCode1.setBackground(new java.awt.Color(254, 254, 254));
        lblCourseCode1.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        lblCourseCode1.setForeground(new java.awt.Color(114, 150, 180));
        lblCourseCode1.setText("Email:");

        txtEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEmailActionPerformed(evt);
            }
        });

        lblCourseName1.setBackground(new java.awt.Color(254, 254, 254));
        lblCourseName1.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        lblCourseName1.setForeground(new java.awt.Color(114, 150, 180));
        lblCourseName1.setText("Contact No:");

        cPhone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cPhoneActionPerformed(evt);
            }
        });

        lblCredits2.setBackground(new java.awt.Color(254, 254, 254));
        lblCredits2.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        lblCredits2.setForeground(new java.awt.Color(114, 150, 180));
        lblCredits2.setText("Name:");

        lblCredits4.setBackground(new java.awt.Color(254, 254, 254));
        lblCredits4.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        lblCredits4.setForeground(new java.awt.Color(114, 150, 180));
        lblCredits4.setText("Request for:");

        cmbRequestType.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select", "Health Care", "Shelter", "Both Health care and Shelter" }));

        lblCredits3.setBackground(new java.awt.Color(254, 254, 254));
        lblCredits3.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        lblCredits3.setForeground(new java.awt.Color(114, 150, 180));
        lblCredits3.setText("Location:");

        javax.swing.GroupLayout addjPanel4Layout = new javax.swing.GroupLayout(addjPanel4);
        addjPanel4.setLayout(addjPanel4Layout);
        addjPanel4Layout.setHorizontalGroup(
            addjPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(addjPanel4Layout.createSequentialGroup()
                .addGroup(addjPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(addjPanel4Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(lblCredits4))
                    .addGroup(addjPanel4Layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addGroup(addjPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(addjPanel4Layout.createSequentialGroup()
                                .addComponent(lblCredits2)
                                .addGap(18, 18, 18)
                                .addComponent(cPerson, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(addjPanel4Layout.createSequentialGroup()
                                .addComponent(lblCredits3)
                                .addGap(18, 18, 18)
                                .addGroup(addjPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(networkJComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(cmbRequestType, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(42, 42, 42)
                        .addGroup(addjPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(addjPanel4Layout.createSequentialGroup()
                                .addGap(45, 45, 45)
                                .addComponent(lblCourseCode1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(addjPanel4Layout.createSequentialGroup()
                                .addComponent(lblCourseName1)
                                .addGap(18, 18, 18)
                                .addComponent(cPhone, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        addjPanel4Layout.setVerticalGroup(
            addjPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(addjPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(addjPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(addjPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(cPerson, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblCredits2))
                    .addGroup(addjPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblCourseName1)
                        .addComponent(cPhone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(addjPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(addjPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblCredits3)
                        .addComponent(networkJComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(addjPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblCourseCode1)
                        .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(addjPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmbRequestType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblCredits4))
                .addContainerGap(22, Short.MAX_VALUE))
        );

        jButton1.setFont(new java.awt.Font("Serif", 1, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(72, 74, 95));
        jButton1.setText("SUBMIT");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        addjPanel3.setBackground(new java.awt.Color(254, 254, 254));
        addjPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createTitledBorder(""), "Personal Details", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Ubuntu", 1, 15), new java.awt.Color(95, 139, 162))); // NOI18N

        lblCourseCode.setBackground(new java.awt.Color(254, 254, 254));
        lblCourseCode.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        lblCourseCode.setForeground(new java.awt.Color(114, 150, 180));
        lblCourseCode.setText("First Name:");

        fName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fNameActionPerformed(evt);
            }
        });

        lblCourseName.setBackground(new java.awt.Color(254, 254, 254));
        lblCourseName.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        lblCourseName.setForeground(new java.awt.Color(114, 150, 180));
        lblCourseName.setText("Last Name:");

        lName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lNameActionPerformed(evt);
            }
        });

        lblkeywords.setBackground(new java.awt.Color(254, 254, 254));
        lblkeywords.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        lblkeywords.setForeground(new java.awt.Color(114, 150, 180));
        lblkeywords.setText("Date of Birth:");

        lblCredits.setBackground(new java.awt.Color(254, 254, 254));
        lblCredits.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        lblCredits.setForeground(new java.awt.Color(114, 150, 180));
        lblCredits.setText("Age:");

        age.setEnabled(false);
        age.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ageActionPerformed(evt);
            }
        });

        lblCredits1.setBackground(new java.awt.Color(254, 254, 254));
        lblCredits1.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        lblCredits1.setForeground(new java.awt.Color(114, 150, 180));
        lblCredits1.setText("Gender: ");

        genderCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Male", "Female", "Declined To Answer" }));

        lblCourseCode2.setBackground(new java.awt.Color(254, 254, 254));
        lblCourseCode2.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        lblCourseCode2.setForeground(new java.awt.Color(114, 150, 180));
        lblCourseCode2.setText("Height:");

        height.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                heightActionPerformed(evt);
            }
        });

        lblCourseCode5.setBackground(new java.awt.Color(254, 254, 254));
        lblCourseCode5.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        lblCourseCode5.setForeground(new java.awt.Color(114, 150, 180));
        lblCourseCode5.setText("ft");

        lblCourseCode3.setBackground(new java.awt.Color(254, 254, 254));
        lblCourseCode3.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        lblCourseCode3.setForeground(new java.awt.Color(114, 150, 180));
        lblCourseCode3.setText("Weight:");

        weight.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                weightActionPerformed(evt);
            }
        });

        lblCourseCode4.setBackground(new java.awt.Color(254, 254, 254));
        lblCourseCode4.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        lblCourseCode4.setForeground(new java.awt.Color(114, 150, 180));
        lblCourseCode4.setText("lbs");

        javax.swing.GroupLayout addjPanel3Layout = new javax.swing.GroupLayout(addjPanel3);
        addjPanel3.setLayout(addjPanel3Layout);
        addjPanel3Layout.setHorizontalGroup(
            addjPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(addjPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(addjPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(addjPanel3Layout.createSequentialGroup()
                        .addGroup(addjPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(addjPanel3Layout.createSequentialGroup()
                                .addGap(14, 14, 14)
                                .addComponent(lblCourseCode))
                            .addGroup(addjPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(lblCredits1)
                                .addComponent(lblkeywords)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(addjPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(addjPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(fName)
                                .addComponent(jdcDOB, javax.swing.GroupLayout.DEFAULT_SIZE, 184, Short.MAX_VALUE))
                            .addComponent(genderCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(addjPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(addjPanel3Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(addjPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(addjPanel3Layout.createSequentialGroup()
                                        .addComponent(lblCourseName)
                                        .addGap(18, 18, 18)
                                        .addComponent(lName, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(addjPanel3Layout.createSequentialGroup()
                                        .addComponent(lblCredits)
                                        .addGap(18, 18, 18)
                                        .addComponent(age, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(129, 129, 129))))
                            .addGroup(addjPanel3Layout.createSequentialGroup()
                                .addGap(34, 34, 34)
                                .addComponent(lblCourseCode2)
                                .addGap(18, 18, 18)
                                .addComponent(height, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblCourseCode5))))
                    .addGroup(addjPanel3Layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addComponent(lblCourseCode3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(weight, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblCourseCode4)))
                .addContainerGap(34, Short.MAX_VALUE))
        );
        addjPanel3Layout.setVerticalGroup(
            addjPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(addjPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(addjPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblCourseCode)
                    .addComponent(lblCourseName)
                    .addComponent(lName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(addjPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(addjPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblkeywords)
                        .addComponent(lblCredits)
                        .addComponent(age, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jdcDOB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(addjPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCredits1)
                    .addComponent(genderCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(height, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblCourseCode2)
                    .addComponent(lblCourseCode5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(addjPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(weight, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblCourseCode3)
                    .addComponent(lblCourseCode4))
                .addGap(0, 18, Short.MAX_VALUE))
        );

        jPanel1.setBackground(new java.awt.Color(254, 254, 254));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Profile Picture", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Ubuntu", 1, 15), new java.awt.Color(95, 139, 162))); // NOI18N

        imgLogo.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        imgLogo.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        btnAttach.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        btnAttach.setForeground(new java.awt.Color(75, 88, 121));
        btnAttach.setText("Attach");
        btnAttach.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAttachActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(imgLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(29, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnAttach, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(60, 60, 60))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(imgLogo, javax.swing.GroupLayout.DEFAULT_SIZE, 179, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(btnAttach)
                .addGap(68, 68, 68))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(addjPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(293, 293, 293)
                            .addComponent(jButton1))
                        .addGroup(layout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(addjPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(24, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(addjPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(addjPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 6, Short.MAX_VALUE))
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1)
                .addGap(18, 18, 18))
        );
    }// </editor-fold>//GEN-END:initComponents
    private void populateComboBox() {
        networkJComboBox.removeAllItems();

        for (Network network : system.getNetworkList()) {
            networkJComboBox.addItem(network);
        }
    }
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        String fname = fName.getText();
        String lname = lName.getText();

        String gender = genderCombo.getSelectedItem().toString();
        String request = cmbRequestType.getSelectedItem().toString();
        String pic = null;
                    try {
                ImageIO.write(needyPicture, "JPG", new File("./src/needyProfilePictures/"+fname + lname +"capture.jpg"));
            } catch (IOException ex) {
                java.util.logging.Logger.getLogger(PersonalDetailsJPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
            }
            String filename = "/needyProfilePictures/" + fname + lname + "capture.jpg";
            pic = filename;

        if (fName.getText().isEmpty() | lName.getText().isEmpty()| height.getText().isEmpty() | weight.getText().isEmpty()|txtEmail.getText().isEmpty()| cPhone.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Please enter all the fields!");
            return;
        } else if(!fName.getText().matches("^[a-zA-Z]+$")){
            JOptionPane.showMessageDialog(null, "Please enter only characters in First Name","Error",JOptionPane.ERROR_MESSAGE);
             return;
        } else if(!lName.getText().matches("^[a-zA-Z]+$")){
            JOptionPane.showMessageDialog(null, "Please enter only characters in Last Name","Error",JOptionPane.ERROR_MESSAGE);
             return;
        } else if(!cPerson.getText().matches("^[a-zA-Z]+$")){
            JOptionPane.showMessageDialog(null, "Please enter only characters in Contact person's Name","Error",JOptionPane.ERROR_MESSAGE);
             return;
        } else if(!txtEmail.getText().matches("^([a-zA-Z0-9_\\-\\.]+)@((\\[[0-9]{1,3}\\.[0-9]{1,3}\\.[0-9]{1,3}\\.)|(([a-zA-Z0-9\\-]+\\.)+))([a-zA-Z]{2,4}|[0-9]{1,3})(\\]?)$")){
            JOptionPane.showMessageDialog(null, "Please enter Valid Email ID!");
            return;
        } else if(!cPhone.getText().matches("^(\\+\\d{1,3}[- ]?)?\\d{10}$") && !cPhone.getText().matches("^\\([0-9]{3}\\)[0-9]{3}-[0-9]{4}$")){
            JOptionPane.showMessageDialog(null, "Please enter Valid Phone No!");
            return;
        }
        try {
            int height1 = Integer.parseInt(height.getText());
            int weight1 = Integer.parseInt(weight.getText());
             DateFormat fmt = new SimpleDateFormat("dd/MM/yyyy");
            DateFormat year = new SimpleDateFormat("yyyy");
            int ageDiff = 0;
            int DOB = Integer.parseInt(year.format(jdcDOB.getDate()));
            ageDiff = 2021-DOB;    
            age.setText(String.valueOf(ageDiff));
             if ((ageDiff > 110) || (ageDiff < 1)) {
                JOptionPane.showMessageDialog(null, "Please enter a Valid birth date!");
                return;
            }
            //            pic = getPic(fname);
            Network network = (Network) networkJComboBox.getSelectedItem();
            //            Network currentNetwork = system.getNetworkList().get(0);
            for (Enterprise ent : network.getEnterpriseDirectory().getEnterpriseList()) {
                if (ent.enterpriseType.equalsIgnoreCase(Enterprise.EnterpriseType.Volunteer.getValue())) {
                    for(UserAccount adminUser : ent.getUserAccountDirectory().getUserAccountList()) {
                        if(adminUser.getRole() instanceof AdminRole) {

                            if(request.equalsIgnoreCase("Health care")){
                                PatientTestRequest req = new PatientTestRequest();

                                req.setPatientid(PROPERTIES);
                                req.setPatientfirstname(fname);
                                req.setPatientlastname(lname);
                                req.setPheight(height1);
                                req.setPweight(weight1);
                                req.setPgender(gender);
                                req.setPimage(pic);
                                req.setTypeOfRequest("AssignHospital");
                                req.setStatus("Awaiting hospital For initial checkup");
                                adminUser.getWorkQueue().getWorkRequestList().add(req);
                                JOptionPane.showMessageDialog(this, "Patient registered succesfully. Treatment request send to HAS");
                            } else if(request.equalsIgnoreCase("Shelter")){
                                ShelterRequest r = new ShelterRequest();
                                r.setTypeOfRequest("AssignShelter");
                                r.setStatus("Awaiting for Shelter");
                                r.setAssignedfor("Assign Shelter");
                                r.setShelterRequestName(fname +" "+ lname);
                                r.setObjectName(fname +" "+ lname);
                                r.setAge(Integer.parseInt(age.getText()));
                                adminUser.getWorkQueue().getWorkRequestList().add(r);
                                JOptionPane.showMessageDialog(this, "Person registered succesfully. Shelter request send to admin");
                            }else if(request.equalsIgnoreCase("Both Health care and Shelter")){
                                ShelterRequest r = new ShelterRequest();
                                r.setPatientid(PROPERTIES);
                                r.setPatientfirstname(fname);
                                r.setPatientlastname(lname);
                                r.setPheight(height1);
                                r.setPweight(weight1);
                                r.setPgender(gender);
                                r.setObjectName(fname +" "+ lname);
                                r.setTypeOfRequest("AssignShelterAndHospital");
                                r.setStatus("Awaiting for Shelter and Treatment");
                                r.setAssignedfor("Assign Shelter and treatment");
                                r.setShelterRequestName(fname +" "+ lname);
                                r.setAge(Integer.parseInt(age.getText()));
                                adminUser.getWorkQueue().getWorkRequestList().add(r);
                                JOptionPane.showMessageDialog(this, "Person registered succesfully. Shelter and Treatment request send to admin");
                            }  else {
                                JOptionPane.showMessageDialog(this, "Select form the options provided");
                                return;
                            }
                            //if (org.toString().equals(has_HealthcareOrg)) {

                                //req.setPimage("Have to upload");

                                //                                req.setReceiver(user);
                                //                                user.getWorkQueue().getWorkRequestList().add(req);

                                //                            }
                            //                            if (org.toString().equals(has_ShelterOrg)) {
                                //
                                //                            }
                            fName.setText("");
                            lName.setText("");
                            height.setText("");
                            weight.setText("");
                        }
                    }
                }
            }
            
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(null, "Please enter number for Age, Height and Weight!");
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void cPhoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cPhoneActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cPhoneActionPerformed

    private void txtEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEmailActionPerformed

    private void fNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fNameActionPerformed

    private void lNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lNameActionPerformed

    private void ageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ageActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ageActionPerformed

    private void heightActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_heightActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_heightActionPerformed

    private void weightActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_weightActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_weightActionPerformed

    private void btnAttachActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAttachActionPerformed
        JFileChooser browseDriverLicenseFile = new JFileChooser();

        //Filter image extensions
        FileNameExtensionFilter fnef = new FileNameExtensionFilter("IMAGES", "png", "jpg", "jpeg");
        browseDriverLicenseFile.addChoosableFileFilter(fnef);
        int showOpenDialogue = browseDriverLicenseFile.showOpenDialog(null);
        if (showOpenDialogue == JFileChooser.APPROVE_OPTION) {
            File selectedImageFile = browseDriverLicenseFile.getSelectedFile();
            String selectedImagePath = selectedImageFile.getAbsolutePath();

            //Display image in JLable
            ImageIcon Ii = new ImageIcon(selectedImagePath);
            //Resize image to fit jlabel
            Image image = Ii.getImage().getScaledInstance(imgLogo.getWidth(), imgLogo.getHeight(), Image.SCALE_SMOOTH);
            imgLogo.setIcon(new ImageIcon(image));

            // construct the buffered image
            BufferedImage bImage = new BufferedImage(image.getWidth(null), image.getHeight(null), BufferedImage.TYPE_INT_RGB);
            Graphics2D bImageGraphics = bImage.createGraphics();
            bImageGraphics.drawImage(image, null, null);
//            RenderedImage rImage = (RenderedImage) bImage;
            needyPicture = (RenderedImage) bImage;
        }
    }//GEN-LAST:event_btnAttachActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel addjPanel3;
    private javax.swing.JPanel addjPanel4;
    private javax.swing.JTextField age;
    private javax.swing.JButton btnAttach;
    private javax.swing.JTextField cPerson;
    private javax.swing.JTextField cPhone;
    private javax.swing.JComboBox<String> cmbRequestType;
    private javax.swing.JTextField fName;
    private javax.swing.JComboBox<String> genderCombo;
    private javax.swing.JTextField height;
    private javax.swing.JLabel imgLogo;
    private javax.swing.JButton jButton1;
    private javax.swing.JPanel jPanel1;
    private com.toedter.calendar.JDateChooser jdcDOB;
    private javax.swing.JTextField lName;
    private javax.swing.JLabel lblCourseCode;
    private javax.swing.JLabel lblCourseCode1;
    private javax.swing.JLabel lblCourseCode2;
    private javax.swing.JLabel lblCourseCode3;
    private javax.swing.JLabel lblCourseCode4;
    private javax.swing.JLabel lblCourseCode5;
    private javax.swing.JLabel lblCourseName;
    private javax.swing.JLabel lblCourseName1;
    private javax.swing.JLabel lblCredits;
    private javax.swing.JLabel lblCredits1;
    private javax.swing.JLabel lblCredits2;
    private javax.swing.JLabel lblCredits3;
    private javax.swing.JLabel lblCredits4;
    private javax.swing.JLabel lblkeywords;
    private javax.swing.JComboBox<Object> networkJComboBox;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField weight;
    // End of variables declaration//GEN-END:variables
}
